/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUIQytetet;
import GUIQytetet.CapturaNombreJugadores;
import GUIQytetet.Dado;
import ModeloQytetet.Qytetet;
import java.util.ArrayList;
import ModeloQytetet.MetodoSalirCarcel;
import ModeloQytetet.Qytetet;
import ModeloQytetet.TipoCasilla;
import javax.swing.JOptionPane;
/**
 *
 * @author merino
 */
public class ControladorQytetet extends javax.swing.JFrame {
    Qytetet modeloQytetet;
    /**
     * Creates new form ControladorQytetet
     */
    public ControladorQytetet() {
        initComponents();
        this.Jugar.setEnabled(true);
        this.SalirCarcelPagando.setEnabled(false);
        this.SalirCarcelDado.setEnabled(false);
        this.AplicarSorpresa.setEnabled(false);
        this.ComprarPropiedad.setEnabled(false);
        this.SiguienteJugador.setEnabled(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        vistaQytetet1 = new GUIQytetet.VistaQytetet();
        SalirCarcelDado = new javax.swing.JButton();
        SalirCarcelPagando = new javax.swing.JButton();
        Jugar = new javax.swing.JButton();
        ComprarPropiedad = new javax.swing.JButton();
        AplicarSorpresa = new javax.swing.JButton();
        SiguienteJugador = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        SalirCarcelDado.setText("Salir Cárcel Dado");
        SalirCarcelDado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirCarcelDadoActionPerformed(evt);
            }
        });

        SalirCarcelPagando.setText("Salir Cárcel Pagando");
        SalirCarcelPagando.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirCarcelPagandoActionPerformed(evt);
            }
        });

        Jugar.setText("Jugar");
        Jugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JugarActionPerformed(evt);
            }
        });

        ComprarPropiedad.setText("Comprar Propiedad");
        ComprarPropiedad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComprarPropiedadActionPerformed(evt);
            }
        });

        AplicarSorpresa.setText("Aplicar Sorpresa");
        AplicarSorpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AplicarSorpresaActionPerformed(evt);
            }
        });

        SiguienteJugador.setText("Siguiente Jugador");
        SiguienteJugador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SiguienteJugadorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(vistaQytetet1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(SalirCarcelPagando, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(SalirCarcelDado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(27, 27, 27)
                        .addComponent(Jugar, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ComprarPropiedad)
                        .addGap(38, 38, 38)
                        .addComponent(AplicarSorpresa)
                        .addGap(45, 45, 45)
                        .addComponent(SiguienteJugador, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(vistaQytetet1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(SalirCarcelDado)
                        .addGap(18, 18, 18)
                        .addComponent(SalirCarcelPagando))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(AplicarSorpresa)
                            .addComponent(SiguienteJugador, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Jugar, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ComprarPropiedad))))
                .addGap(0, 38, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SalirCarcelDadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirCarcelDadoActionPerformed
        // TODO add your handling code here:
        //Qytetet modeloQytetet = Qytetet.getInstance();

        boolean resultado = modeloQytetet.intentarSalirCarcel(MetodoSalirCarcel.TIRANDODADO);
 
        this.SalirCarcelPagando.setEnabled(false);
        this.SalirCarcelDado.setEnabled(false);
        if(resultado){
            JOptionPane.showMessageDialog(this, "Sales de la cárcel");
            this.Jugar.setEnabled(true);
        }
        else{
            JOptionPane.showMessageDialog(this, "No sales de la cárcel");
            this.SiguienteJugador.setEnabled(true);
        }
        //this.vistaQytetet1.actualizar(modeloQytetet);
        actualizar(modeloQytetet);

    }//GEN-LAST:event_SalirCarcelDadoActionPerformed

    private void SalirCarcelPagandoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirCarcelPagandoActionPerformed
        // TODO add your handling code here:
        Qytetet modeloQytetet = Qytetet.getInstance();

        boolean resultado = modeloQytetet.intentarSalirCarcel(MetodoSalirCarcel.PAGANDOLIBERTAD);
        
        this.SalirCarcelPagando.setEnabled(false);
        this.SalirCarcelDado.setEnabled(false);
        if(resultado){
            JOptionPane.showMessageDialog(this, "Sales de la cárcel");
            this.Jugar.setEnabled(true);
        }
        else{
            JOptionPane.showMessageDialog(this, "No sales de la cárcel");
            this.SiguienteJugador.setEnabled(true);
        }
        //this.vistaQytetet1.actualizar(modeloQytetet);
        actualizar(modeloQytetet);

    }//GEN-LAST:event_SalirCarcelPagandoActionPerformed

    private void JugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JugarActionPerformed
        // TODO add your handling code here:
        //Qytetet modeloQytetet = Qytetet.getInstance();
        boolean resultado = modeloQytetet.jugar();
            this.ComprarPropiedad.setEnabled(false);
            this.SalirCarcelPagando.setEnabled(false);
            this.SalirCarcelDado.setEnabled(false);
            this.AplicarSorpresa.setEnabled(false);
            this.SiguienteJugador.setEnabled(false);
               //por tanto permito pasar al siguiente jugador  
            //desactivo jugar porque ya se ha movido
            this.Jugar.setEnabled(false);

        if(resultado){ // si ha salido true, tiene propietario
            this.SiguienteJugador.setEnabled(true);
        }
        else{ // ahora la casilla no tiene propietario pero puede ser edificable o no
            
            //si es edificable:
            if(modeloQytetet.getJugadorActual().getCasillaActual().getTipo() == TipoCasilla.CALLE){
                this.ComprarPropiedad.setEnabled(true);
                this.SiguienteJugador.setEnabled(true);
            }
            
            else if(modeloQytetet.getJugadorActual().getCasillaActual().getTipo() == TipoCasilla.SORPRESA){
                this.AplicarSorpresa.setEnabled(true);

            //this.SalirCarcelPagando.setEnabled(false);
            //this.SalirCarcelDado.setEnabled(false);
            //por tanto permito pasar al siguiente jugador  
            //desactivo jugar porque ya se ha movido
            //this.Jugar.setEnabled(false);
            }  
            else{
               this.SiguienteJugador.setEnabled(true);

            }

        } 
        //this.vistaQytetet1.actualizar(modeloQytetet);        
        actualizar(modeloQytetet);

    }//GEN-LAST:event_JugarActionPerformed

    private void ComprarPropiedadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComprarPropiedadActionPerformed
        // TODO add your handling code here:
        //Qytetet modeloQytetet = Qytetet.getInstance();

        boolean resultado = modeloQytetet.comprarTituloPropiedad();
 
        this.SalirCarcelPagando.setEnabled(false);
        this.SalirCarcelDado.setEnabled(false);
        this.ComprarPropiedad.setEnabled(false);
        this.Jugar.setEnabled(false);
        this.AplicarSorpresa.setEnabled(false);
        JOptionPane.showMessageDialog(this, "Has comprado una propiedad");
       
        this.SiguienteJugador.setEnabled(true);

       // this.vistaQytetet1.actualizar(modeloQytetet);
       actualizar(modeloQytetet);

    }//GEN-LAST:event_ComprarPropiedadActionPerformed

    private void AplicarSorpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AplicarSorpresaActionPerformed
        // TODO add your handling code here:
        //Qytetet modeloQytetet = Qytetet.getInstance();

        boolean resultado = modeloQytetet.aplicarSorpresa();
 
        this.SalirCarcelPagando.setEnabled(false);
        this.SalirCarcelDado.setEnabled(false);
        this.Jugar.setEnabled(false);
        this.ComprarPropiedad.setEnabled(false);
        this.AplicarSorpresa.setEnabled(false);

   
        JOptionPane.showMessageDialog(this, "Has aplicado la sorpresa");
        
        this.SiguienteJugador.setEnabled(true);

        //this.vistaQytetet1.actualizar(modeloQytetet);
        actualizar(modeloQytetet);
    }//GEN-LAST:event_AplicarSorpresaActionPerformed
    
    public void habilitarComenzarTurno(){
       // Qytetet modeloQytetet = Qytetet.getInstance();

        this.ComprarPropiedad.setEnabled(false);
        this.SiguienteJugador.setEnabled(false);
        this.AplicarSorpresa.setEnabled(false);
        this.SalirCarcelPagando.setEnabled(false);
        this.Jugar.setEnabled(true);
        this.SalirCarcelDado.setEnabled(false);
        if(modeloQytetet.getJugadorActual().getEncarcelado()){
            this.SalirCarcelPagando.setEnabled(true);
            this.Jugar.setEnabled(false);
            this.SalirCarcelDado.setEnabled(true);
        }
    }
    
    private void SiguienteJugadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SiguienteJugadorActionPerformed
        // TODO add your handling code here:
        //Qytetet modeloQytetet = Qytetet.getInstance();
        habilitarComenzarTurno();
        modeloQytetet.siguienteJugador();
        habilitarComenzarTurno();

                
        actualizar(modeloQytetet);

    }//GEN-LAST:event_SiguienteJugadorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       Qytetet modeloQytetet = Qytetet.getInstance();
       ControladorQytetet controladorQytetet = new ControladorQytetet();
       CapturaNombreJugadores capturaNombres = new CapturaNombreJugadores(controladorQytetet, true);
       ArrayList<String> nombres = capturaNombres.obtenerNombres();
       modeloQytetet.inicializarJuego(nombres);
       
       Dado.createInstance(controladorQytetet);
       controladorQytetet.actualizar(modeloQytetet);
       
       controladorQytetet.setVisible(true); //esta debe ser la ULTIMA LINEA DEL MAIN
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AplicarSorpresa;
    private javax.swing.JButton ComprarPropiedad;
    private javax.swing.JButton Jugar;
    private javax.swing.JButton SalirCarcelDado;
    private javax.swing.JButton SalirCarcelPagando;
    private javax.swing.JButton SiguienteJugador;
    private GUIQytetet.VistaQytetet vistaQytetet1;
    // End of variables declaration//GEN-END:variables
  public void actualizar(Qytetet aux){
       // habilitarComenzarTurno();
        modeloQytetet = aux;
        vistaQytetet1.actualizar(aux);
        repaint();
        revalidate();
  }
    
}
